DROP TABLE IF EXISTS product;

CREATE TABLE IF NOT EXISTS product(id varchar(32) unsigned not null primary key,name varchar(32),price int,tenant_id varchar(32),created_by varchar(32),updated_by varchar(32),created_time date,updated_time date, is_deleted int(1));

INSERT INTO product(id, name, price, tenant_id, created_by, updated_by, created_time, updated_time, is_deleted) VALUES ('1', '苹果', 20, null, null, null, null, null, 0),
('2', '梨', 10, null, null ,null, null, null, 0),
('3', '桃子', 123, null, null ,null, null, null, 0),
('4', '香蕉', 11, null, null ,null, null, null, 0),
('5', '猕猴桃', 50, null, null ,null, null, null, 0),
('6', '桔子', 33, null, null ,null, null, null, 0),
('7', '菠萝', 90, null, null ,null, null, null, 0),
('8', '芒果', 766, null, null ,null, null, null, 0),
('9', '红枣', 29, null, null ,null, null, null, 0),
('10', '榴莲', 990, null, null ,null, null, null, 0),
('11', '柚子', 291, null, null ,null, null, null, 0),
('12', '小番茄', 200, null, null ,null, null, null, 0);
CREATE TABLE IF NOT EXISTS cc_chain(
    id int  not null primary key,    parent_id int   ,    chain_type_id int  not null ,    chain_name varchar(255) not null ,    chain_code varchar(255) not null ,    chain_name_en varchar(255)  ,    path varchar(255)  ,    description varchar(255)  ,    business_license varchar(255)  ,    version int  not null ,    remark varchar(255)  ,    dr tinyint not null ,    created_by varchar(255) not null ,    created_time datetime not null ,    updated_by varchar(255) not null ,    updated_time datetime not null ,    app_id int  not null ,    tenant_id varchar(255) not null );
CREATE TABLE IF NOT EXISTS cc_store_grade(
    id int  not null primary key,    store_grade_name varchar(255) not null ,    store_grade_code varchar(255) not null ,    store_grade_name_en varchar(255)  ,    description varchar(255)  ,    version int  not null ,    remark varchar(255)  ,    dr tinyint not null ,    created_by varchar(255) not null ,    created_time datetime not null ,    updated_by varchar(255) not null ,    updated_time datetime not null ,    app_id int  not null ,    tenant_id varchar(255) not null );
CREATE TABLE IF NOT EXISTS cc_store_grade_relation(
    id int  not null primary key,    store_id int  not null ,    store_grade_Id int  not null ,    version int  not null ,    remark varchar(255)  ,    dr tinyint not null ,    created_by varchar(255) not null ,    created_time datetime not null ,    updated_by varchar(255) not null ,    updated_time datetime not null ,    app_id int  not null ,    tenant_id varchar(255) not null );
CREATE TABLE IF NOT EXISTS cc_store_distributor_relation(
    id int  not null primary key,    store_id varchar(255) not null ,    distributor_id varchar(255) not null ,    grade_system_id varchar(255)  ,    version int  not null ,    remark varchar(255)  ,    dr tinyint not null ,    created_by varchar(255) not null ,    created_time datetime not null ,    updated_by varchar(255) not null ,    updated_time datetime not null ,    app_id int  not null ,    tenant_id varchar(255) not null );
CREATE TABLE IF NOT EXISTS cc_bank_account(
    id int  not null primary key,    bank_id int  not null ,    bank_branch_name varchar(255) not null ,    account_no varchar(255) not null ,    bank_code varchar(255) not null ,    version int  not null ,    remark varchar(255)  ,    dr tinyint not null ,    created_by varchar(255) not null ,    created_time datetime not null ,    updated_by varchar(255) not null ,    updated_time datetime not null ,    app_id int  not null ,    tenant_id varchar(255) not null );
CREATE TABLE IF NOT EXISTS cc_bank(
    id int  not null primary key,    bank_name varchar(255) not null ,    version int  not null ,    remark varchar(255)  ,    dr tinyint not null ,    created_by varchar(255) not null ,    created_time datetime not null ,    updated_by varchar(255) not null ,    updated_time datetime not null ,    app_id int  not null ,    tenant_id varchar(255) not null );
CREATE TABLE IF NOT EXISTS cc_distributor_grade_system(
    id int  not null primary key,    grade_system_name varchar(255) not null ,    grade_system_code varchar(255) not null ,    description varchar(255)  ,    version int  not null ,    remark varchar(255)  ,    dr tinyint not null ,    created_by varchar(255) not null ,    created_time datetime not null ,    updated_by varchar(255) not null ,    updated_time datetime not null ,    app_id int  not null ,    tenant_id varchar(255) not null );
CREATE TABLE IF NOT EXISTS cc_distributor_bank(
    id int  not null primary key,    distributor_id int  not null ,    bank_account_id int  not null ,    version int  not null ,    remark varchar(255)  ,    dr tinyint not null ,    created_by varchar(255) not null ,    created_time datetime not null ,    updated_by varchar(255) not null ,    updated_time datetime not null ,    app_id int  not null ,    tenant_id varchar(255) not null );
CREATE TABLE IF NOT EXISTS cc_chain_bank(
    id int  not null primary key,    bank_account_id int  not null ,    chain_id int  not null ,    version int  not null ,    remark varchar(255)  ,    dr tinyint not null ,    created_by varchar(255) not null ,    created_time datetime not null ,    updated_by varchar(255) not null ,    updated_time datetime not null ,    app_id int  not null ,    tenant_id varchar(255) not null );
CREATE TABLE IF NOT EXISTS cc_distributor_grade(
    id int  not null primary key,    parent_id int  not null ,    root tinyint not null ,    distributor_grade_name varchar(255) not null ,    distributor_grade_code varchar(255) not null ,    grade_system_id int   ,    version int  not null ,    remark varchar(255)  ,    description varchar(255)  ,    dr tinyint not null ,    created_by varchar(255) not null ,    created_time datetime not null ,    updated_by varchar(255) not null ,    updated_time datetime not null ,    app_id int  not null ,    tenant_id varchar(255) not null );
CREATE TABLE IF NOT EXISTS cc_distributor_area(
    id int  not null primary key,    distributor_id int  not null ,    area_id int  not null ,    version int  not null ,    remark varchar(255)  ,    dr tinyint not null ,    created_by varchar(255) not null ,    created_time datetime not null ,    updated_by varchar(255) not null ,    updated_time datetime not null ,    app_id int  not null ,    tenant_id varchar(255) not null );
CREATE TABLE IF NOT EXISTS cc_distributor(
    id int  not null primary key,    distributor_type tinyint not null ,    distributor_name varchar(255) not null ,    distributor_name_en varchar(255)  ,    distributor_code varchar(255)  ,    business_type varchar(255)  ,    business_license_no varchar(255)  ,    business_license varchar(255)  ,    credit_value int   ,    principal_name varchar(255)  ,    principal_id_card varchar(255)  ,    qualification varchar(255)  ,    address varchar(255)  ,    enable tinyint not null ,    version int  not null ,    remark varchar(255)  ,    dr tinyint not null ,    created_by varchar(255) not null ,    created_time datetime not null ,    updated_by varchar(255) not null ,    updated_time datetime not null ,    app_id int  not null ,    tenant_id varchar(255) not null );
CREATE TABLE IF NOT EXISTS cc_area(
    dr tinyint not null ,    created_by varchar(255) not null ,    created_time datetime not null ,    updated_by varchar(255) not null ,    updated_time datetime not null ,    app_id int  not null ,    tenant_id varchar(255) not null ,    id int  not null primary key,    parent_id int   ,    area_type_id int  not null ,    area_name varchar(255) not null ,    area_code varchar(255) not null ,    area_name_en varchar(255)  ,    path varchar(255)  ,    description varchar(255)  ,    version int  not null ,    remark varchar(255)  );
CREATE TABLE IF NOT EXISTS cc_store_area(
    id int  not null primary key,    area_id int  not null ,    store_id int  not null ,    version int  not null ,    remark varchar(255)  ,    dr tinyint not null ,    created_by varchar(255) not null ,    created_time datetime not null ,    updated_by varchar(255) not null ,    updated_time datetime not null ,    app_id int  not null ,    tenant_id varchar(255) not null );
CREATE TABLE IF NOT EXISTS cc_store_chain(
    id int  not null primary key,    store_id int  not null ,    chain_id int  not null ,    version int  not null ,    remark varchar(255)  ,    dr tinyint not null ,    created_by varchar(255) not null ,    created_time datetime not null ,    updated_by varchar(255) not null ,    updated_time datetime not null ,    app_id int  not null ,    tenant_id varchar(255) not null );
CREATE TABLE IF NOT EXISTS cc_area_type(
    id int  not null primary key,    parent_id int  not null ,    limit_parent tinyint not null ,    area_type_name varchar(255) not null ,    area_type_code varchar(255) not null ,    area_type_name_en varchar(255)  ,    path varchar(255)  ,    description varchar(255)  ,    version int  not null ,    remark varchar(255)  ,    dr tinyint not null ,    created_by varchar(255) not null ,    created_time datetime not null ,    updated_by varchar(255) not null ,    updated_time datetime not null ,    app_id int  not null ,    tenant_id varchar(255) not null );
CREATE TABLE IF NOT EXISTS cc_store_type(
    id int  not null primary key,    store_type_name varchar(255) not null ,    store_type_code varchar(255) not null ,    store_type_name_en varchar(255)  ,    description varchar(255)  ,    version int  not null ,    remark varchar(255)  ,    dr tinyint not null ,    created_by varchar(255) not null ,    created_time datetime not null ,    updated_by varchar(255) not null ,    updated_time datetime not null ,    app_id int  not null ,    tenant_id varchar(255) not null );
CREATE TABLE IF NOT EXISTS cc_distributor_grade_relation(
    id int  not null primary key,    distributor_id int  not null ,    distributor_grade_id int  not null ,    version int  not null ,    remark varchar(255)  ,    dr tinyint not null ,    created_by varchar(255) not null ,    created_time datetime not null ,    updated_by varchar(255) not null ,    updated_time datetime not null ,    app_id int  not null ,    tenant_id varchar(255) not null );
CREATE TABLE IF NOT EXISTS cc_store(
    id int  not null primary key,    store_name varchar(255) not null ,    store_code varchar(255) not null ,    store_name_en varchar(255)  ,    client_name varchar(255)  ,    client_code varchar(255)  ,    store_address varchar(255)  ,    store_phone varchar(255)  ,    enable tinyint not null ,    version int  not null ,    remark varchar(255)  ,    dr tinyint not null ,    created_by varchar(255) not null ,    created_time datetime not null ,    updated_by varchar(255) not null ,    updated_time datetime not null ,    app_id int  not null ,    tenant_id varchar(255) not null );
CREATE TABLE IF NOT EXISTS cc_store_type_relation(
    id int  not null primary key,    store_id int  not null ,    store_type_Id int  not null ,    version int  not null ,    remark varchar(255)  ,    dr tinyint not null ,    created_by varchar(255) not null ,    created_time datetime not null ,    updated_by varchar(255) not null ,    updated_time datetime not null ,    app_id int  not null ,    tenant_id varchar(255) not null );
CREATE TABLE IF NOT EXISTS cc_chain_type(
    id int  not null primary key,    parent_id int  not null ,    limit_parent tinyint not null ,    chain_type_name varchar(255) not null ,    chain_type_code varchar(255) not null ,    chain_type_name_en varchar(255)  ,    description varchar(255)  ,    version int  not null ,    remark varchar(255)  ,    dr tinyint not null ,    created_by varchar(255) not null ,    created_time datetime not null ,    updated_by varchar(255) not null ,    updated_time datetime not null ,    app_id int  not null ,    tenant_id varchar(255) not null );
